//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trials.GTC.Website.TrackCentral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAndRole", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Web.Services")]
    [System.SerializableAttribute()]
    public partial class UserAndRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TracksResults", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Web.Services")]
    [System.SerializableAttribute()]
    public partial class TracksResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trials.GTC.Website.TrackCentral.Track[] TracksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFilter {
            get {
                return this.IsFilterField;
            }
            set {
                if ((this.IsFilterField.Equals(value) != true)) {
                    this.IsFilterField = value;
                    this.RaisePropertyChanged("IsFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trials.GTC.Website.TrackCentral.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Data")]
    [System.SerializableAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HyperlinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ScoreCoefficientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmittedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SubmittedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimeGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimePlatinumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimeSilverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimeUltimateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrialsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrialsVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((this.DifficultyField.Equals(value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasThumb {
            get {
                return this.HasThumbField;
            }
            set {
                if ((this.HasThumbField.Equals(value) != true)) {
                    this.HasThumbField = value;
                    this.RaisePropertyChanged("HasThumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hyperlink {
            get {
                return this.HyperlinkField;
            }
            set {
                if ((object.ReferenceEquals(this.HyperlinkField, value) != true)) {
                    this.HyperlinkField = value;
                    this.RaisePropertyChanged("Hyperlink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkId {
            get {
                return this.LinkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkIdField, value) != true)) {
                    this.LinkIdField = value;
                    this.RaisePropertyChanged("LinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ScoreCoefficient {
            get {
                return this.ScoreCoefficientField;
            }
            set {
                if ((this.ScoreCoefficientField.Equals(value) != true)) {
                    this.ScoreCoefficientField = value;
                    this.RaisePropertyChanged("ScoreCoefficient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Submitted {
            get {
                return this.SubmittedField;
            }
            set {
                if ((this.SubmittedField.Equals(value) != true)) {
                    this.SubmittedField = value;
                    this.RaisePropertyChanged("Submitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmittedBy {
            get {
                return this.SubmittedByField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmittedByField, value) != true)) {
                    this.SubmittedByField = value;
                    this.RaisePropertyChanged("SubmittedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmittedOn {
            get {
                return this.SubmittedOnField;
            }
            set {
                if ((this.SubmittedOnField.Equals(value) != true)) {
                    this.SubmittedOnField = value;
                    this.RaisePropertyChanged("SubmittedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeGold {
            get {
                return this.TimeGoldField;
            }
            set {
                if ((this.TimeGoldField.Equals(value) != true)) {
                    this.TimeGoldField = value;
                    this.RaisePropertyChanged("TimeGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimePlatinum {
            get {
                return this.TimePlatinumField;
            }
            set {
                if ((this.TimePlatinumField.Equals(value) != true)) {
                    this.TimePlatinumField = value;
                    this.RaisePropertyChanged("TimePlatinum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeSilver {
            get {
                return this.TimeSilverField;
            }
            set {
                if ((this.TimeSilverField.Equals(value) != true)) {
                    this.TimeSilverField = value;
                    this.RaisePropertyChanged("TimeSilver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeUltimate {
            get {
                return this.TimeUltimateField;
            }
            set {
                if ((this.TimeUltimateField.Equals(value) != true)) {
                    this.TimeUltimateField = value;
                    this.RaisePropertyChanged("TimeUltimate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialsType {
            get {
                return this.TrialsTypeField;
            }
            set {
                if ((this.TrialsTypeField.Equals(value) != true)) {
                    this.TrialsTypeField = value;
                    this.RaisePropertyChanged("TrialsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialsVersion {
            get {
                return this.TrialsVersionField;
            }
            set {
                if ((this.TrialsVersionField.Equals(value) != true)) {
                    this.TrialsVersionField = value;
                    this.RaisePropertyChanged("TrialsVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Data")]
    [System.SerializableAttribute()]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompetitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompetition {
            get {
                return this.IsCompetitionField;
            }
            set {
                if ((this.IsCompetitionField.Equals(value) != true)) {
                    this.IsCompetitionField = value;
                    this.RaisePropertyChanged("IsCompetition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Time", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Data")]
    [System.SerializableAttribute()]
    public partial class Time : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Time1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TrackIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Faults {
            get {
                return this.FaultsField;
            }
            set {
                if ((this.FaultsField.Equals(value) != true)) {
                    this.FaultsField = value;
                    this.RaisePropertyChanged("Faults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkId {
            get {
                return this.LinkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkIdField, value) != true)) {
                    this.LinkIdField = value;
                    this.RaisePropertyChanged("LinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rider {
            get {
                return this.RiderField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderField, value) != true)) {
                    this.RiderField = value;
                    this.RaisePropertyChanged("Rider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Time1 {
            get {
                return this.Time1Field;
            }
            set {
                if ((this.Time1Field.Equals(value) != true)) {
                    this.Time1Field = value;
                    this.RaisePropertyChanged("Time1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((this.TrackIdField.Equals(value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessagesResult", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Data")]
    [System.SerializableAttribute()]
    public partial class GetMessagesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventSummaryResult", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Data")]
    [System.SerializableAttribute()]
    public partial class EventSummaryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FaultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Faults {
            get {
                return this.FaultsField;
            }
            set {
                if ((this.FaultsField.Equals(value) != true)) {
                    this.FaultsField = value;
                    this.RaisePropertyChanged("Faults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rider {
            get {
                return this.RiderField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderField, value) != true)) {
                    this.RiderField = value;
                    this.RaisePropertyChanged("Rider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTrack", Namespace="http://schemas.datacontract.org/2004/07/Trials.GTC.Web.Services")]
    [System.SerializableAttribute()]
    public partial class NewTrack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HyperlinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScoreCoeffientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimePlatinumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeSilverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeUltimateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrialsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrialsVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((this.DifficultyField.Equals(value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hyperlink {
            get {
                return this.HyperlinkField;
            }
            set {
                if ((object.ReferenceEquals(this.HyperlinkField, value) != true)) {
                    this.HyperlinkField = value;
                    this.RaisePropertyChanged("Hyperlink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkId {
            get {
                return this.LinkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkIdField, value) != true)) {
                    this.LinkIdField = value;
                    this.RaisePropertyChanged("LinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScoreCoeffient {
            get {
                return this.ScoreCoeffientField;
            }
            set {
                if ((this.ScoreCoeffientField.Equals(value) != true)) {
                    this.ScoreCoeffientField = value;
                    this.RaisePropertyChanged("ScoreCoeffient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Submitted {
            get {
                return this.SubmittedField;
            }
            set {
                if ((this.SubmittedField.Equals(value) != true)) {
                    this.SubmittedField = value;
                    this.RaisePropertyChanged("Submitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeGold {
            get {
                return this.TimeGoldField;
            }
            set {
                if ((this.TimeGoldField.Equals(value) != true)) {
                    this.TimeGoldField = value;
                    this.RaisePropertyChanged("TimeGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimePlatinum {
            get {
                return this.TimePlatinumField;
            }
            set {
                if ((this.TimePlatinumField.Equals(value) != true)) {
                    this.TimePlatinumField = value;
                    this.RaisePropertyChanged("TimePlatinum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeSilver {
            get {
                return this.TimeSilverField;
            }
            set {
                if ((this.TimeSilverField.Equals(value) != true)) {
                    this.TimeSilverField = value;
                    this.RaisePropertyChanged("TimeSilver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeUltimate {
            get {
                return this.TimeUltimateField;
            }
            set {
                if ((this.TimeUltimateField.Equals(value) != true)) {
                    this.TimeUltimateField = value;
                    this.RaisePropertyChanged("TimeUltimate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialsType {
            get {
                return this.TrialsTypeField;
            }
            set {
                if ((this.TrialsTypeField.Equals(value) != true)) {
                    this.TrialsTypeField = value;
                    this.RaisePropertyChanged("TrialsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialsVersion {
            get {
                return this.TrialsVersionField;
            }
            set {
                if ((this.TrialsVersionField.Equals(value) != true)) {
                    this.TrialsVersionField = value;
                    this.RaisePropertyChanged("TrialsVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="TrackCentral.TrackCentral")]
    public interface TrackCentral {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/ResetUser", ReplyAction="urn:TrackCentral/ResetUserResponse")]
        string ResetUser(string username, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/ResetUser", ReplyAction="urn:TrackCentral/ResetUserResponse")]
        System.Threading.Tasks.Task<string> ResetUserAsync(string username, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/RegisterUser", ReplyAction="urn:TrackCentral/RegisterUserResponse")]
        Trials.GTC.Website.TrackCentral.UserAndRole RegisterUser(string username, string password, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/RegisterUser", ReplyAction="urn:TrackCentral/RegisterUserResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.UserAndRole> RegisterUserAsync(string username, string password, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/LoginUser", ReplyAction="urn:TrackCentral/LoginUserResponse")]
        Trials.GTC.Website.TrackCentral.UserAndRole LoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/LoginUser", ReplyAction="urn:TrackCentral/LoginUserResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.UserAndRole> LoginUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTracks", ReplyAction="urn:TrackCentral/GetTracksResponse")]
        Trials.GTC.Website.TrackCentral.TracksResults GetTracks(int pageNumber, int resultsPerPage, System.Nullable<int> trials, System.Nullable<int> type, System.Nullable<int> difficulty, string creator, string keyword, string sortName, bool sortDirection, System.Guid[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTracks", ReplyAction="urn:TrackCentral/GetTracksResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.TracksResults> GetTracksAsync(int pageNumber, int resultsPerPage, System.Nullable<int> trials, System.Nullable<int> type, System.Nullable<int> difficulty, string creator, string keyword, string sortName, bool sortDirection, System.Guid[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTrack", ReplyAction="urn:TrackCentral/GetTrackResponse")]
        Trials.GTC.Website.TrackCentral.Track GetTrack(string linkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTrack", ReplyAction="urn:TrackCentral/GetTrackResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Track> GetTrackAsync(string linkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTags", ReplyAction="urn:TrackCentral/GetTagsResponse")]
        Trials.GTC.Website.TrackCentral.Tag[] GetTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTags", ReplyAction="urn:TrackCentral/GetTagsResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Tag[]> GetTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTimes", ReplyAction="urn:TrackCentral/GetTimesResponse")]
        Trials.GTC.Website.TrackCentral.Time[] GetTimes(System.Guid trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetTimes", ReplyAction="urn:TrackCentral/GetTimesResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Time[]> GetTimesAsync(System.Guid trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetMessages", ReplyAction="urn:TrackCentral/GetMessagesResponse")]
        Trials.GTC.Website.TrackCentral.GetMessagesResult[] GetMessages(System.Guid trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetMessages", ReplyAction="urn:TrackCentral/GetMessagesResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.GetMessagesResult[]> GetMessagesAsync(System.Guid trackId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetEventSummary", ReplyAction="urn:TrackCentral/GetEventSummaryResponse")]
        Trials.GTC.Website.TrackCentral.EventSummaryResult[] GetEventSummary(System.Guid tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/GetEventSummary", ReplyAction="urn:TrackCentral/GetEventSummaryResponse")]
        System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.EventSummaryResult[]> GetEventSummaryAsync(System.Guid tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/NewTrack", ReplyAction="urn:TrackCentral/NewTrackResponse")]
        bool NewTrack(Trials.GTC.Website.TrackCentral.NewTrack n);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/NewTrack", ReplyAction="urn:TrackCentral/NewTrackResponse")]
        System.Threading.Tasks.Task<bool> NewTrackAsync(Trials.GTC.Website.TrackCentral.NewTrack n);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/DeleteTrack", ReplyAction="urn:TrackCentral/DeleteTrackResponse")]
        bool DeleteTrack(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/DeleteTrack", ReplyAction="urn:TrackCentral/DeleteTrackResponse")]
        System.Threading.Tasks.Task<bool> DeleteTrackAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/SubmitTime", ReplyAction="urn:TrackCentral/SubmitTimeResponse")]
        bool SubmitTime(System.Guid userId, System.Guid trackId, string linkId, string rider, System.TimeSpan time, int faults, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/SubmitTime", ReplyAction="urn:TrackCentral/SubmitTimeResponse")]
        System.Threading.Tasks.Task<bool> SubmitTimeAsync(System.Guid userId, System.Guid trackId, string linkId, string rider, System.TimeSpan time, int faults, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/NewMessage", ReplyAction="urn:TrackCentral/NewMessageResponse")]
        bool NewMessage(System.Guid userId, System.Guid trackId, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TrackCentral/NewMessage", ReplyAction="urn:TrackCentral/NewMessageResponse")]
        System.Threading.Tasks.Task<bool> NewMessageAsync(System.Guid userId, System.Guid trackId, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrackCentralChannel : Trials.GTC.Website.TrackCentral.TrackCentral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackCentralClient : System.ServiceModel.ClientBase<Trials.GTC.Website.TrackCentral.TrackCentral>, Trials.GTC.Website.TrackCentral.TrackCentral {
        
        public TrackCentralClient() {
        }
        
        public TrackCentralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackCentralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackCentralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackCentralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ResetUser(string username, string emailAddress) {
            return base.Channel.ResetUser(username, emailAddress);
        }
        
        public System.Threading.Tasks.Task<string> ResetUserAsync(string username, string emailAddress) {
            return base.Channel.ResetUserAsync(username, emailAddress);
        }
        
        public Trials.GTC.Website.TrackCentral.UserAndRole RegisterUser(string username, string password, string emailAddress) {
            return base.Channel.RegisterUser(username, password, emailAddress);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.UserAndRole> RegisterUserAsync(string username, string password, string emailAddress) {
            return base.Channel.RegisterUserAsync(username, password, emailAddress);
        }
        
        public Trials.GTC.Website.TrackCentral.UserAndRole LoginUser(string username, string password) {
            return base.Channel.LoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.UserAndRole> LoginUserAsync(string username, string password) {
            return base.Channel.LoginUserAsync(username, password);
        }
        
        public Trials.GTC.Website.TrackCentral.TracksResults GetTracks(int pageNumber, int resultsPerPage, System.Nullable<int> trials, System.Nullable<int> type, System.Nullable<int> difficulty, string creator, string keyword, string sortName, bool sortDirection, System.Guid[] tags) {
            return base.Channel.GetTracks(pageNumber, resultsPerPage, trials, type, difficulty, creator, keyword, sortName, sortDirection, tags);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.TracksResults> GetTracksAsync(int pageNumber, int resultsPerPage, System.Nullable<int> trials, System.Nullable<int> type, System.Nullable<int> difficulty, string creator, string keyword, string sortName, bool sortDirection, System.Guid[] tags) {
            return base.Channel.GetTracksAsync(pageNumber, resultsPerPage, trials, type, difficulty, creator, keyword, sortName, sortDirection, tags);
        }
        
        public Trials.GTC.Website.TrackCentral.Track GetTrack(string linkId) {
            return base.Channel.GetTrack(linkId);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Track> GetTrackAsync(string linkId) {
            return base.Channel.GetTrackAsync(linkId);
        }
        
        public Trials.GTC.Website.TrackCentral.Tag[] GetTags() {
            return base.Channel.GetTags();
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Tag[]> GetTagsAsync() {
            return base.Channel.GetTagsAsync();
        }
        
        public Trials.GTC.Website.TrackCentral.Time[] GetTimes(System.Guid trackId) {
            return base.Channel.GetTimes(trackId);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.Time[]> GetTimesAsync(System.Guid trackId) {
            return base.Channel.GetTimesAsync(trackId);
        }
        
        public Trials.GTC.Website.TrackCentral.GetMessagesResult[] GetMessages(System.Guid trackId) {
            return base.Channel.GetMessages(trackId);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.GetMessagesResult[]> GetMessagesAsync(System.Guid trackId) {
            return base.Channel.GetMessagesAsync(trackId);
        }
        
        public Trials.GTC.Website.TrackCentral.EventSummaryResult[] GetEventSummary(System.Guid tagId) {
            return base.Channel.GetEventSummary(tagId);
        }
        
        public System.Threading.Tasks.Task<Trials.GTC.Website.TrackCentral.EventSummaryResult[]> GetEventSummaryAsync(System.Guid tagId) {
            return base.Channel.GetEventSummaryAsync(tagId);
        }
        
        public bool NewTrack(Trials.GTC.Website.TrackCentral.NewTrack n) {
            return base.Channel.NewTrack(n);
        }
        
        public System.Threading.Tasks.Task<bool> NewTrackAsync(Trials.GTC.Website.TrackCentral.NewTrack n) {
            return base.Channel.NewTrackAsync(n);
        }
        
        public bool DeleteTrack(System.Guid id) {
            return base.Channel.DeleteTrack(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTrackAsync(System.Guid id) {
            return base.Channel.DeleteTrackAsync(id);
        }
        
        public bool SubmitTime(System.Guid userId, System.Guid trackId, string linkId, string rider, System.TimeSpan time, int faults, string link) {
            return base.Channel.SubmitTime(userId, trackId, linkId, rider, time, faults, link);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitTimeAsync(System.Guid userId, System.Guid trackId, string linkId, string rider, System.TimeSpan time, int faults, string link) {
            return base.Channel.SubmitTimeAsync(userId, trackId, linkId, rider, time, faults, link);
        }
        
        public bool NewMessage(System.Guid userId, System.Guid trackId, string body) {
            return base.Channel.NewMessage(userId, trackId, body);
        }
        
        public System.Threading.Tasks.Task<bool> NewMessageAsync(System.Guid userId, System.Guid trackId, string body) {
            return base.Channel.NewMessageAsync(userId, trackId, body);
        }
    }
}
